version: "3.9"

services:
  sql-server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    hostname: sql-server
    container_name: sql-server
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=something
      - MSSQL_PID=Express
    volumes:
      - sqlvolume:/var/opt/mssql
  mongodb-server:
    image: mongo:4.4.9
    hostname: mongodb-server
    container_name: mongodb-server
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: something
      MONGO_INITDB_ROOT_PASSWORD: something
    volumes:
      - mongovolume:/data/db

volumes:
  sqlvolume:
  mongovolume:  
